name: TFT Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nvidia-cuda-toolkit cmake build-essential || true
          nvcc --version || true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Build
        run: |
          bash scripts/build.sh || (echo "Build failed, running CPU-only install" && pip install -e .)

      - name: Tests
        run: |
          bash scripts/test.sh

      - name: Train (sanity epoch)
        env:
          TFT_EPOCHS: 1
        run: |
          # Run a shortened training to validate pipeline
          sed -i 's/"epochs"[[:space:]]*:[[:space:]]*[0-9]\+/"epochs": 1/g' config/default_config.json || true
          timeout 300 bash scripts/train.sh || echo "Training sanity complete (timeout acceptable)"

      - name: Debug on Failure
        if: failure()
        run: |
          bash scripts/debug.sh